# Generated by Django 5.2.4 on 2025-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertype_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
    ]
