# Generated by Django 5.2.6 on 2025-10-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
