# Generated by Django 5.2.4 on 2025-10-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
