# Generated by Django 5.2.7 on 2025-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0003_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del negocio (ej: 6.2442)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del negocio (ej: -75.5812)', max_digits=9, null=True),
        ),
    ]
