# Generated by Django 5.2.4 on 2025-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0004_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='menu_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
