# Generated by Django 5.2.4 on 2025-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0005_business_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='numero de visitas al negocio'),
        ),
    ]
