# Generated by Django 5.2.4 on 2025-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdely', '0006_business_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
