# Generated by Django 5.2.6 on 2025-10-02 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appdely', '0003_delete_usertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Promoción',
                'verbose_name_plural': 'Tipos de Promociones',
            },
        ),
        migrations.CreateModel(
            name='NoticiaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(help_text='Resumen para vista previa', max_length=200)),
                ('tipo_noticia', models.CharField(choices=[('nuevo_plato', 'Nuevo Plato'), ('evento', 'Evento Especial'), ('apertura', 'Nueva Apertura'), ('renovacion', 'Renovación'), ('chef', 'Chef Invitado'), ('premio', 'Premio/Reconocimiento'), ('general', 'Noticia General')], default='general', max_length=20)),
                ('imagen_destacada', models.URLField(blank=True, null=True)),
                ('galeria_imagenes', models.TextField(blank=True, help_text='URLs de imágenes separadas por comas')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar en banner principal')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('me_gusta', models.PositiveIntegerField(default=0)),
                ('compartidas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='appdely.business')),
            ],
            options={
                'verbose_name': 'Noticia de Restaurante',
                'verbose_name_plural': 'Noticias de Restaurantes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título llamativo de la promoción', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la promoción')),
                ('descripcion_corta', models.CharField(help_text='Descripción breve para tarjetas', max_length=150)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 25.00 para 25%', max_digits=5, null=True)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio diaria', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin diaria', null=True)),
                ('dias_validos', models.CharField(default='1234567', help_text='1=Lunes, 7=Domingo', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('limite_personas', models.PositiveIntegerField(blank=True, help_text='Límite de personas que pueden usar la promoción', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('imagen_secundaria', models.URLField(blank=True, null=True)),
                ('terminos_condiciones', models.TextField(blank=True, help_text='Términos y condiciones específicos')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('me_gusta', models.PositiveIntegerField(default=0)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='appdely.business')),
                ('tipo_promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.tipopromocion')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comentario', models.TextField(blank=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Promoción',
                'verbose_name_plural': 'Usos de Promociones',
                'unique_together': {('usuario', 'promocion')},
            },
        ),
    ]
